models/contact.py
from utils.db import db


class Contact(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    fullname = db.Column(db.String(50), nullable=False)
    email = db.Column(db.String(100), nullable=False)
    phone = db.Column(db.String(50), nullable=False)

    def __init__(self, fullname, email, phone):
        self.fullname = fullname
        self.email = email
        self.phone = phone

app.py
from flask import Flask
from routes.contacts import contacts
from flask_sqlalchemy import SQLAlchemy

# , template_folder='src/templates
app = Flask(__name__)
app.secret_key = b'_5#y2L"F4Q8z\n\xec]/'
#
app.config['SQLALCHEMY_DATABASE_URI'] = 'mysql://root:my_secret@localhost/contacts_db'
# app.config['SQLALCHEMY_DATABASE_URI'] = 'postgresql://postgres:my_secret@localhost/contacts_app'

app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = False

SQLAlchemy(app)
'''
Los blueprints permiten organizar las rutas de la aplicacion, para llamar a esas rutas
desde el archivo de configuracion registramos la blueprint como se muestra a continuacion
'''

app.register_blueprint(contacts)

routes/contacts.py
from flask import Blueprint, render_template, request, redirect, url_for, flash
from models.contact import Contact
from utils.db import db

contacts = Blueprint('contacts', __name__)

'''
Blueprints: un blueprint permite orgnizar las rutas haciendolas mas descriptivas
a continuacion se muestra como se hace uso de blueprint. 
--> esta blue print se registra en el archivo app.py
'''


@contacts.route('/')
def index():
    contacts = Contact.query.all()
    return render_template('index.html', contacts=contacts)


@contacts.route('/new', methods=['POST'])
def add():
    fullname = request.form['fullname']
    email = request.form['email']
    phone = request.form['phone']

    new_contact = Contact(fullname, email, phone)

    db.session.add(new_contact)
    db.session.commit()
    flash('Contact added correctly')
    return redirect(url_for('contacts.index'))


@contacts.route('/update/<int:id>', methods=['GET', 'POST'])
def update(id):
    if request.method == 'POST':
        contact = Contact.query.get(id)
        contact.fullname = request.form['fullname']
        contact.email = request.form['email']
        contact.phone = request.form['phone']
        db.session.commit()

        flash('Contact updated correctly')
        return redirect(url_for('contacts.index'))

    contact = Contact.query.get(id)
    return render_template('update.html', contact=contact)


@contacts.route('/delete/<int:id>')
def delete(id):
    contact = Contact.query.get(id)
    db.session.delete(contact)
    db.session.commit()
    flash('Contact deleted correctly')
    return redirect(url_for('contacts.index'))


@contacts.route('/about')
def about():
    pass

templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="{{url_for('static', filename='css/index.css')}}">
  <title>{% block title %} {% endblock %}</title>
</head>

<body>

  <nav>
    <h1 id="title">Contacts app</h1>
  </nav>

  <div class="container">

    {% with messages = get_flashed_messages() %}
    {% if messages %}

    <div class="flash">
      {% for message in messages %}
      <p>{{ message }}</p>
      {% endfor %}
    </div>

    {% endif %}
    {% endwith %}
    {% block container %}

    {% endblock %}
  </div>
  <script src="{{ url_for('static', filename = 'js/index.js')}}"></script>
</body>

</html>

templates/index.html
{% extends 'base.html' %}

{% block title %} Contacts {% endblock %}

{% block container %}
<div id="form">
  <h1 class="section-title">Create a new contact</h1>
  <form action="/new" method="POST">
    <input type="text" id="fullname" name="fullname" placeholder="Enter the full name" required><br>
    <input type="email" id="email" name="email" placeholder="Enter an email" required><br>
    <input type="text" id="phone" name="phone" placeholder="Enter a telephone number" required><br>
    <input type="submit" value="Save"><br>
  </form>
</div>

<div id="contacts">
  <h1 class="section-title">List of contacts</h1>
  {% for contact in contacts %}
  <div class="contact">
    <h4 class="name">{{contact.fullname}}</h4>
    <p class="email">{{contact.email}}</p>
    <p class="phone">{{contact.phone}}</p>
    <a href="{{ url_for('contacts.update', id=contact.id) }}" class="btn btn-update">Update</a>
    <a href="{{ url_for('contacts.delete', id=contact.id) }}" class="btn btn-delete">Delete</a>
  </div>
  {% endfor %}
</div>
{% endblock %}

templates/update.html
{% extends 'base.html' %}

{% block title %} Update {% endblock %}

{% block container %}
<div id="btn-back">
  <a href="{{url_for('contacts.index')}}" class="btn-back">Back</a>
</div>

<div id="form">
  <h1 class="section-title">Update a contact</h1>
  <form action="{{url_for('contacts.update', id=contact.id)}}" method="POST">
    <input type="text" id="fullname" name="fullname" value="{{contact.fullname}}" placeholder="Enter the full name" required><br>
    <input type="email" id="email" name="email" value="{{contact.email}}" placeholder="Enter an email" required><br>
    <input type="text" id="phone" name="phone" value="{{contact.phone}}" placeholder="Enter a telephone number" required><br>
    <input type="submit" value="Update">
  </form>
</div>
{% endblock %}